spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: user-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: user-service-application