server:
  port: 8889

spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: git-config-server
  application:
    name: config-service-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ErincK/Java6ConfigServer.git
          default-label: main
          skip-ssl-validation: true
          username: ErincK
          password: ${java6configpassword}