server:
  port: 7072

spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: java6user
      password: root
      database: userdb

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root

jwt:
  secretkey: ${JAVA_SECRETKEY}
  audience: ${JAVA6_AUDIENCE}
  issuer: ${JAVA6_ISSUER}

rabbitmq:
  exchange-auth: auth-exchange
  registerkey: register-key
  queueRegister: register-queue